
title: Cairopractice
description: A blog about Cairo and Starknet
url: https://cairopractice.com
paginate: 20
baseurl: ""
permalink: pretty

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# safe: true
lsi: false
incremental: true

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - .python-version
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Milan Cermak
  url: https://milancermak.com
twitter_username: milancermak
github_username: milancermak

# Custom vars
version: 3.0.0

# Navbar page list
# nav:
#   - title: Blog
#     url: /archive
#   - title: About
#     url: /about
